{
 "title": "充电曲线",
 "tags": [
  "tesla",
  "teslaCustom"
 ],
 "time": { "from": "now-10y", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "car_id",
    "label": "Car",
    "query": "SELECT name AS __text, id AS __value FROM cars ORDER BY display_priority ASC, name ASC;"
   },
   {
    "name": "base_url",
    "query": "select base_url from settings limit 1;"
   },
   { "name": "min_power", "label": "Minimum maximum power (kW)", "query": "75" },
   { "name": "max_power", "label": "Maximum power (kW)", "query": "260" }
  ]
 },
 "panels": [
  {
   "title": "每次充电最大功率",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 17, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "WITH data AS (\n    SELECT ROUND(MAX(c.charger_power) / 5, 0) * 5 AS \"power\"\n    FROM charging_processes cp\n    LEFT JOIN charges c ON cp.id = c.charging_process_id\n    WHERE \n      $__timeFilter(c.date) \n      AND cp.car_id = $car_id \n      AND cp.charge_energy_added > 0.01 \n      AND c.fast_charger_present\n    GROUP BY cp.id\n)\nSELECT power AS \"Power [kW]\", COUNT(power) AS n\nFROM data\nWHERE power > 22\nGROUP BY 1\nORDER BY 1 ASC\n"
    }
   ]
  },
  {
   "title": "快充网络",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 0 },
   "targets": [
    {
     "rawSql": "WITH charges_summary AS (\n    SELECT\n        cp.id,\n        COALESCE(geo.name, CONCAT_WS(', ', COALESCE(addr.name, nullif(CONCAT_WS(' ', addr.road, addr.house_number), '')), addr.city)) AS location,\n        COUNT(c.charging_process_id)\n    FROM\n        charging_processes cp\n    LEFT JOIN \n        addresses addr ON addr.id = address_id\n    LEFT JOIN\n        geofences geo ON geo.id = geofence_id\n    LEFT JOIN\n        charges c ON cp.id = c.charging_process_id\n    WHERE\n        $__timeFilter(date) AND\n        cp.car_id = $car_id AND cp.charge_energy_added > 0.01 AND c.fast_charger_present \n    GROUP BY 1, 2\n)\nSELECT \n    CASE\n        WHEN location ILIKE '%supercharger%' THEN 'Tesla SuperCharger'\n        ELSE 'Other DC Stations' END AS location,\n    COUNT(location) AS n\nFROM charges_summary\nGROUP BY 1"
    }
   ]
  },
  {
   "title": "特斯拉超充充电曲线",
   "type": "xychart",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 6 },
   "targets": [
    {
     "rawSql": "SELECT\n\tc.battery_level as \"SOC [%]\",\n\tround(avg(c.charger_power), 0) as \"Power [kW]\",\n\tc.charging_process_id as \"charging_process_id\",\n\tCOALESCE(g.name, a.name) || ' ' || to_char(c.date, 'YYYY-MM-dd') as \"Charge\"\nFROM charges c\nJOIN charging_processes p ON p.id = c.charging_process_id \nJOIN addresses a ON a.id = p.address_id\nLEFT JOIN geofences g ON g.id = p.geofence_id\nWHERE\n\t$__timeFilter(date)\n\tAND charger_power > 0\n\tAND c.fast_charger_present\n\tAND (a.display_name ILIKE '%supercharger%' OR a.name ILIKE '%supercharger%' OR g.name ILIKE '%supercharger%')\n\tAND c.charging_process_id IN (\n\t\tSELECT c.charging_process_id\n\t\tFROM charging_processes cp\n\t\tLEFT JOIN charges c ON cp.id = c.charging_process_id\n\t\tWHERE \n\t\t\t$__timeFilter(c.date)\n\t\t\tAND cp.car_id = $car_id\n\t\t\tAND c.fast_charger_present\n\t\tGROUP BY 1\n\t\tHAVING MAX(c.charger_power) BETWEEN $min_power AND $max_power\n\t)\nGROUP BY c.battery_level, c.charging_process_id, a.name, g.name, to_char(c.date, 'YYYY-MM-dd')"
    },
    {
     "rawSql": "SELECT\n\tc.battery_level as \"B - SOC [%]\",\n\tAVG(charger_power) as \"B - Avg Power [kW]\"\nFROM charges c\nJOIN charging_processes p ON p.id = c.charging_process_id \nJOIN addresses a ON a.id = p.address_id\nLEFT JOIN geofences g ON g.id = p.geofence_id\nWHERE\n\t$__timeFilter(date)\n\tAND charger_power > 0\n\tAND c.fast_charger_present\n\tAND (a.display_name ILIKE '%supercharger%' OR a.name ILIKE '%supercharger%' OR g.name ILIKE '%supercharger%')\n\tAND c.charging_process_id IN (\n\t\tSELECT c.charging_process_id\n\t\tFROM charging_processes cp\n\t\tLEFT JOIN charges c ON cp.id = c.charging_process_id\n\t\tWHERE \n\t\t\t$__timeFilter(c.date)\n\t\t\tAND cp.car_id = $car_id\n\t\t\tAND c.fast_charger_present\n\t\tGROUP BY 1\n\t\tHAVING MAX(c.charger_power) BETWEEN $min_power AND $max_power\n\t)\nGROUP BY battery_level"
    }
   ]
  },
  {
   "title": "其它直流充电曲线",
   "type": "xychart",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 6 },
   "targets": [
    {
     "rawSql": "SELECT\n\tc.battery_level as \"SOC [%]\", \n\tround(avg(c.charger_power), 0) as \"Power [kW]\",\n\tc.charging_process_id as \"charging_process_id\",\n\tCOALESCE(g.name, a.name) || ' ' || to_char(c.date, 'YYYY-MM-dd') as \"Charge\"\nFROM charges c\nJOIN charging_processes p ON p.id = c.charging_process_id \nJOIN addresses a ON a.id = p.address_id\nLEFT JOIN geofences g ON g.id = p.geofence_id\nWHERE\n\t$__timeFilter(date)\n\tAND p.car_id = $car_id\n\tAND c.fast_charger_present\n\tAND c.charger_power > 0.01\n\tAND CASE \n\t\tWHEN (p.geofence_id IS NOT NULL) THEN (a.name NOT ILIKE '%supercharger%' AND g.name NOT ILIKE '%supercharger%')\n\t\tELSE a.name NOT ILIKE '%supercharger%'\n\tEND\n\tAND c.charging_process_id IN (\n\t\tSELECT c.charging_process_id\n\t\tFROM charging_processes cp\n\t\tLEFT JOIN charges c ON cp.id = c.charging_process_id\n\t\tWHERE \n\t\t\t$__timeFilter(c.date)\n\t\t\tAND cp.car_id = $car_id\n\t\t\tAND c.fast_charger_present\n\t\tGROUP BY 1\n\t\tHAVING MAX(c.charger_power) BETWEEN $min_power AND $max_power\n\t)\nGROUP BY c.battery_level, c.charging_process_id, a.name, g.name, to_char(c.date, 'YYYY-MM-dd')"
    },
    {
     "rawSql": "SELECT\n\tc.battery_level as \"B - SOC [%]\",\n\tAVG(charger_power) as \"B - Avg Power [kW]\"\nFROM\n\tcharges c\nJOIN charging_processes p ON p.id = c.charging_process_id \nJOIN addresses a ON a.id = p.address_id\nLEFT JOIN geofences g ON g.id = p.geofence_id\nWHERE\n\t$__timeFilter(date)\n\tAND p.car_id = $car_id\n\tAND charger_power > 22\n\tAND c.fast_charger_present\n\tAND CASE \n\t\tWHEN (p.geofence_id IS NOT NULL) THEN (a.name NOT ILIKE '%supercharger%' AND g.name NOT ILIKE '%supercharger%')\n\t\tELSE a.name NOT ILIKE '%supercharger%'\n\tEND\n\tAND c.charging_process_id IN (\n\t\tSELECT c.charging_process_id\n\t\tFROM charging_processes cp\n\t\tLEFT JOIN charges c ON cp.id = c.charging_process_id\n\t\tWHERE \n\t\t\t$__timeFilter(c.date)\n\t\t\tAND cp.car_id = $car_id\n\t\t\tAND c.fast_charger_present\n\t\tGROUP BY 1\n\t\tHAVING MAX(c.charger_power) BETWEEN $min_power AND $max_power\n\t)\nGROUP BY battery_level"
    }
   ]
  }
 ]
}