{
 "title": "驾驶上限数据",
 "tags": [
  "tesla",
  "teslaCustom"
 ],
 "time": { "from": "now-6M", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "car_id",
    "label": "Car",
    "query": "SELECT name AS __text, id AS __value FROM cars ORDER BY display_priority ASC, name ASC;"
   },
   {
    "name": "base_url",
    "query": "select base_url from settings limit 1;"
   },
   {
    "name": "length_unit",
    "query": "select unit_of_length from settings limit 1;"
   },
   { "name": "min_avg_speed", "label": "Minimum average speed", "query": "50" }
  ]
 },
 "panels": [
  {
   "title": "充电前最大行驶里程",
   "type": "table",
   "gridPos": { "h": 19, "w": 10, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "WITH ranges AS (\n\tSELECT end_date, COALESCE(LAG(start_date) OVER(ORDER BY start_date DESC), now()) AS next_start_date \n\tFROM charging_processes\n\tWHERE \n\t\tcar_id = $car_id\n\t\tAND $__timeFilter(start_date)\n), data AS (\n\tSELECT \n\t\tr.end_date AS date, \n\t\tMAX(p.odometer) - MIN(p.odometer) AS distance,\n\t\tMAX(p.battery_level) AS max_battery_level, \n\t\tMIN(p.battery_level) AS min_battery_level\n\tFROM positions p\n\tINNER JOIN ranges r ON p.date BETWEEN r.end_date AND r.next_start_date\n\tWHERE \n\t\tcar_id = 1\n\tGROUP BY 1\n), res AS (\n\tSELECT\n\t\t(round(extract(epoch FROM r.end_date) - 10) * 1000) AS start_date_ts,\n\t\t(round(extract(epoch FROM r.next_start_date) + 10) * 1000) AS end_date_ts,\n\t\tr.end_date AS date,\n\t\tr.next_start_date AS next_start_date,\n\t\t(dat.distance / (SUM(d.duration_min)::numeric / 60)) AS avg_speed,\n\t\t(max_battery_level - min_battery_level) AS battery_needed,\n\t\tdat.distance AS distance,\n\t\t((dat.distance::decimal * 100) / (max_battery_level - min_battery_level)) AS max_distance\n\tFROM \n\t\tdrives d\n\tINNER JOIN ranges r ON d.start_date BETWEEN r.end_date AND r.next_start_date\n\tINNER JOIN data dat ON r.end_date = dat.date\n\tWHERE \n\t\td.car_id = $car_id\n\tGROUP BY 1, 2, 3, 4, 6, 7\n\tHAVING \n\t\tSUM(d.distance) > 0\n\t\tAND (max_battery_level - min_battery_level) > 0\n\tORDER BY distance DESC\n\tLIMIT 18\n)\nSELECT\n\tstart_date_ts,\n\tend_date_ts,\n\tdate,\n\tnext_start_date,\n\tconvert_km(avg_speed::numeric, '$length_unit') AS avg_speed_[[length_unit]]h,\n\tbattery_needed,\n\tconvert_km(distance::numeric, '$length_unit') AS distance,\n\tconvert_km(max_distance::numeric, '$length_unit') AS max_distance\nFROM res"
    }
   ]
  },
  {
   "title": "信息",
   "type": "text",
   "gridPos": { "h": 1, "w": 4, "x": 10, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  inserted_at AS \"time\",\n  efficiency\nFROM cars\nWHERE\n  $__timeFilter(inserted_at)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "过去12个月",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT to_char(end_date,'YYYY-MM') as \"Date\",\r\n       convert_km((SUM(distance))::numeric, '$length_unit') as \"Distance\"\r\nFROM drives\r\nWHERE \r\n  end_date BETWEEN (date_trunc('month', now()) - interval '11 month') AND NOW()\r\n  AND car_id = $car_id\r\nGROUP BY 1\r\nORDER BY 1;"
    }
   ]
  },
  {
   "title": "单次行驶距离中位数",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT convert_km((percentile_disc(0.5) WITHIN GROUP (ORDER BY distance))::numeric, '$length_unit') as \"distance_$length_unit\"\nFROM drives\nWHERE car_id = $car_id AND $__timeFilter(start_date);"
    }
   ]
  },
  {
   "title": "每天行驶距离中位数",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 10, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "WITH since as (\n\tSELECT date FROM positions\n\tWHERE car_id = $car_id\n\tORDER BY date ASC\n\tLIMIT 1\n),\nactual AS (\n\tSELECT\n\t\tdate_trunc('day', start_date)::date AS date,\n\t\tsum(distance) AS distance\n\tFROM drives\n\tWHERE car_id = $car_id\n\tGROUP BY 1\n),\nbase_line AS (\n\tSELECT date_trunc('day', dd)::date AS date\n  FROM generate_series((select date from since), NOW(), '1 day'::interval) dd\n),\ncombined as (\n  SELECT base_line.date, COALESCE(actual.distance, 0) as distance\n  FROM base_line\n  LEFT JOIN actual ON actual.date = base_line.date\n  WHERE $__timeFilter(base_line.date)\n)\nSELECT convert_km((percentile_disc(0.5) WITHIN GROUP (ORDER BY distance))::numeric, '$length_unit') AS \"distance_$length_unit\"\nFROM combined;"
    }
   ]
  },
  {
   "title": "推测月度里程",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 10, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "WITH first_position AS (\n\tSELECT date, odometer\n\tFROM positions\n\tWHERE car_id = $car_id AND $__timeFilter(date)\n\tORDER BY date ASC\n\tLIMIT 1\n),\nlast_position AS (\n\tSELECT date, odometer\n\tFROM positions\n\tWHERE car_id = $car_id AND $__timeFilter(date)\n\tORDER BY date DESC\n\tLIMIT 1\n)\nSELECT\n\tconvert_km((((SELECT odometer FROM last_position) - (SELECT odometer\tFROM first_position)) /\n\tEXTRACT(days FROM (SELECT date FROM last_position) - (SELECT date\tFROM first_position)) * \n\t(365/12))::numeric, '$length_unit') AS \"mileage_$length_unit\";"
    }
   ]
  },
  {
   "title": "平均月度里程",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 7 },
   "targets": [
    {
     "rawSql": "WITH data AS (\n\tSELECT to_char(end_date,'MM') as \"month_n\",\n\t\tto_char(end_date,'YY') as \"year_n\",\n       to_char(end_date,'Month') as \"month\",\n       SUM(distance)::numeric as \"distance\"\n\tFROM drives\n\tWHERE \n\t  car_id = $car_id\n\t  AND distance > 0\n\tGROUP BY 1, 2, 3\n\tORDER BY 1\n)\nSELECT \n\td.month_n as \"month_number\",\n\td.month as \"Month\",\n\tconvert_km(AVG(d.distance)::numeric, '$length_unit') as \"Distance\"\nFROM data d\nGROUP BY 1, 2\nORDER BY 1 ASC"
    }
   ]
  },
  {
   "title": "推测年度里程",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 10, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "WITH first_position AS (\n\tSELECT date, odometer\n\tFROM positions\n\tWHERE car_id = $car_id AND $__timeFilter(date)\n\tORDER BY date ASC\n\tLIMIT 1\n),\nlast_position AS (\n\tSELECT date, odometer\n\tFROM positions\n\tWHERE car_id = $car_id AND $__timeFilter(date)\n\tORDER BY date DESC\n\tLIMIT 1\n)\nSELECT\n\tconvert_km(((lp.odometer - fp.odometer) /\n\tEXTRACT(days FROM lp.date - fp.date) * \n\t365)::numeric, '$length_unit') AS \"mileage_$length_unit\" from first_position as fp, last_position as lp;"
    }
   ]
  },
  {
   "title": "平均车速 - 最近10次驾驶",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 10, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "WITH data AS (\n\tSELECT \n\t\tdistance / ((round(extract(epoch FROM end_date)) - round(extract(epoch FROM start_date))) / 3600) AS avg_speed\n\tFROM drives\n\tWHERE \n\t\tdistance > 1\n\t\tAND car_id = $car_id\n\tORDER BY start_date DESC\n\tLIMIT 10\n)\nSELECT convert_km(AVG(avg_speed)::numeric, '$length_unit') AS avg_speed_[[length_unit]]h\nFROM data"
    }
   ]
  },
  {
   "title": "每年里程",
   "type": "barchart",
   "gridPos": { "h": 5, "w": 10, "x": 14, "y": 14 },
   "targets": [
    {
     "rawSql": "SELECT to_char(end_date,'YYYY') as \"Year\",\r\n       convert_km((sum(distance))::numeric, '$length_unit') as \"Distance\"\r\nFROM drives\r\nWHERE \r\n  car_id = $car_id\r\nGROUP BY 1\r\nORDER BY 1 ASC;"
    }
   ]
  },
  {
   "title": "平均速度",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 10, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "WITH data AS (\n\tSELECT \n\t\tdistance / ((round(extract(epoch FROM end_date)) - round(extract(epoch FROM start_date))) / 3600) AS avg_speed\n\tFROM drives\n\tWHERE \n\t\tdistance > 1\n\t\tAND car_id = $car_id\n\t\tAND $__timeFilter(start_date)\n)\nSELECT convert_km(AVG(avg_speed)::numeric, '$length_unit') AS avg_speed_[[length_unit]]h\nFROM data"
    }
   ]
  }
 ]
}